name: vits
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - bzip2=1.0.8
  - ca-certificates=2025.12.2
  - expat=2.7.4
  - ld_impl_linux-64=2.44
  - libexpat=2.7.4
  - libffi=3.4.4
  - libgcc=15.2.0
  - libgcc-ng=15.2.0
  - libgomp=15.2.0
  - libnsl=2.0.0
  - libstdcxx=15.2.0
  - libstdcxx-ng=15.2.0
  - libuuid=1.41.5
  - libxcb=1.17.0
  - libzlib=1.3.1
  - ncurses=6.5
  - openssl=3.0.19
  - packaging=25.0
  - pip=25.3
  - pthread-stubs=0.3
  - python=3.10.19
  - readline=8.3
  - setuptools=80.10.2
  - sqlite=3.51.1
  - tk=8.6.15
  - tzdata=2025c
  - wheel=0.46.3
  - xorg-libx11=1.8.12
  - xorg-libxau=1.0.12
  - xorg-libxdmcp=1.1.5
  - xorg-xorgproto=2024.1
  - xz=5.6.4
  - zlib=1.3.1
  - pip:
      - absl-py==2.4.0
      - audioread==3.1.0
      - certifi==2026.1.4
      - cffi==2.0.0
      - charset-normalizer==3.4.4
      - click==8.3.1
      - cmake==3.26.4
      - coloredlogs==15.0.1
      - cycler==0.12.1
      - cython==0.29.21
      - decorator==5.2.1
      - ffmpeg==1.4
      - filelock==3.20.0
      - flatbuffers==25.12.19
      - fsspec==2025.12.0
      - g2pk2==0.0.3
      - grpcio==1.76.0
      - humanfriendly==10.0
      - idna==3.11
      - jaconv==0.4.1
      - jamo==0.4.1
      - jinja2==3.1.6
      - joblib==1.5.3
      - kiwisolver==1.4.9
      - ko-pron==1.3
      - librosa==0.8.0
      - llvmlite==0.46.0
      - markdown==3.10.1
      - markdown-it-py==4.0.0
      - markupsafe==2.1.5
      - matplotlib==3.3.1
      - mdurl==0.1.2
      - ml-dtypes==0.5.4
      - monotonic-align==1.0.0
      - mpmath==1.3.0
      - networkx==3.4.2
      - nltk==3.9.2
      - numba==0.63.1
      - numpy==1.23.5
      - nvidia-cublas-cu11==11.11.3.6
      - nvidia-cuda-cupti-cu11==11.8.87
      - nvidia-cuda-nvrtc-cu11==11.8.89
      - nvidia-cuda-runtime-cu11==11.8.89
      - nvidia-cudnn-cu11==9.1.0.70
      - nvidia-cufft-cu11==10.9.0.58
      - nvidia-curand-cu11==10.3.0.86
      - nvidia-cusolver-cu11==11.4.1.48
      - nvidia-cusparse-cu11==11.7.5.86
      - nvidia-nccl-cu11==2.21.5
      - nvidia-nvtx-cu11==11.8.86
      - onnx==1.20.1
      - onnx-ir==0.1.15
      - onnx-simplifier==0.4.36
      - onnxruntime==1.23.2
      - onnxscript==0.6.0
      - pillow==12.0.0
      - platformdirs==4.5.1
      - pooch==1.9.0
      - protobuf==6.33.5
      - pycparser==3.0
      - pygments==2.19.2
      - pyopenjtalk==0.2.0
      - pyparsing==3.3.2
      - pysoundfile==0.9.0.post1
      - python-dateutil==2.9.0.post0
      - python-mecab-ko==1.3.7
      - python-mecab-ko-dic==2.1.1.post2
      - regex==2026.1.15
      - requests==2.32.5
      - resampy==0.4.3
      - rich==14.3.2
      - scikit-learn==1.7.2
      - scipy==1.10.1
      - six==1.17.0
      - soundfile==0.13.1
      - sympy==1.14.0
      - tensorboard==2.20.0
      - tensorboard-data-server==0.7.2
      - threadpoolctl==3.6.0
      - torch==2.7.1+cu118
      - torchaudio==2.7.1+cu118
      - torchvision==0.22.1+cu118
      - tqdm==4.67.3
      - triton==3.3.1
      - typing-extensions==4.15.0
      - unidecode==1.1.1
      - urllib3==2.6.3
      - werkzeug==3.1.5
